apiVersion: apps/v1
kind: Deployment
metadata:
  name: "jwt-istio-spike"
  namespace: main
  labels:
    app: jwt-istio-spike
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-istio-spike
  progressDeadlineSeconds: 120
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: jwt-istio-spike
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: "docker/default"
    spec:
      securityContext:
        runAsNonRoot: false
        fsGroup: 65534
      containers:
        - name: app
          image: "dgkanatsios/simpleapp"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.1"
              memory: "300Mi"
            limits:
              cpu: "0.2"
              memory: "600Mi"
          securityContext:
            runAsUser: 20000
            runAsGroup: 20000
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: jwt-istio-spike
  namespace: main
  labels:
    app: jwt-istio-spike
    service: jwt-istio-spike
spec:
  selector:
    app: jwt-istio-spike
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jwt-istio-spike
  namespace: main
spec:
  hosts:
  - "*"
  gateways:
  - private
  - public
  http:
  - match:
    - uri:
        prefix: "/jwt-istio-spike/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: jwt-istio-spike
        port:
          number: 8080
---
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: jwt-istio-spike
  namespace: main
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: "ISSUER"
    jwks: |
      { "keys": [{"kty":"RSA","n":"4pL-O8LnvzpX8asAwmSLqpUjJhX4mYbqiwzTn96Qe9Ts32KSSsoA0GBQuQFbVLmy4zVYXNyQ1_XXcs4eKrJFezZo0labTWQftP95WGNpUGH3UdEHlxcAU8Cl4zNpragpFPX_R9f06RSQmsk8XP4iBBHj_dELuGLMShj59KDisXKrVmm4T2csN_HhlHZJEpkrnRkERRSVKn9XVCtodQWMtSR259CTv8fAvvsXQE1LcXLJiRUW_o4DaGXtCUy83Ts2jX9MdFE_OzahwafZAHFhzsvpG_UJkQnFxomC67PIslBpJrCty48GwsI3DPcLgqfvCviTQQ-IhVvhq5AFHcfCfw","e":"AQAB","kid":"5fe6d2426a8f111647c8912de7349c4d1d5a8b849de5f4aa683275af8ee06684"}] }

---
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: jwt-istio-spike
  namespace: main
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: DENY
  rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]
